#### Create a dataset that lists the cars that are either SUV, Wagon, Minivan, or Pickup. For each car, you are required to include Vehicle Name, Vehicle type (i.e., SUV, Wagon, Minivan, or Pickup truck), Retail Price, Engine Size, HP, City MPG, Hwy MPG, Weight, and Wheel Base in the dataset. The data specifications are as follows:

> The header (i.e., the name of each column in the dataset) of this data should sequentially include “name”, “type”, “retail_price”, “engine_size”, “hp”, “mpg_city”, “mpg_hwy”, “weight”, and “wheel_base”.

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
data = pd.read_csv('2004car.csv')

In [3]:
data

,Vehicle Name,Small/Sporty/ Compact/Large Sedan,Sports Car,SUV,Wagon,Minivan,Pickup,AWD,RWD,Retail Price,Dealer Cost,Engine Size (l),Cyl,HP,City MPG,Hwy MPG,Weight,Wheel Base,Len,Width
0,Acura 3.5 RL 4dr,1,0,0,0,0,0,0,0,43755,39014,3.5,6,225,18,24,3880,115,197,72
1,Acura 3.5 RL w/Navigation 4dr,1,0,0,0,0,0,0,0,46100,41100,3.5,6,225,18,24,3893,115,197,72
2,Acura MDX,0,0,1,0,0,0,1,0,36945,33337,3.5,6,265,17,23,4451,106,189,77
3,Acura NSX coupe 2dr manual S,0,1,0,0,0,0,0,1,89765,79978,3.2,6,290,17,24,3153,100,174,71
4,Acura RSX Type S 2dr,1,0,0,0,0,0,0,0,23820,21761,2.0,4,200,24,31,2778,101,172,68
5,Acura TL 4dr,1,0,0,0,0,0,0,0,33195,30299,3.2,6,270,20,28,3575,108,186,72
6,Acura TSX 4dr,1,0,0,0,0,0,0,0,26990,24647,2.4,4,200,22,29,3230,105,183,69
7,Audi A4 1.8T 4dr,1,0,0,0,0,0,0,0,25940,23508,1.8,4,170,22,31,3252,104,179,70
8,Audi A4 3.0 4dr,1,0,0,0,0,0,0,0,31840,28846,3.0,6,220,20,28,3462,104,179,70
9,Audi A4 3.0 convertible 2dr,1,0,0,0,0,0,0,0,42490,38325,3.0,6,220,20,27,3814,105,180,70
10,Audi A4 3.0 Quattro 4dr auto,1,0,0,0,0,0,1,0,34480,31388,3.0,6,220,18,25,3627,104,179,70
11,Audi A4 3.0 Quattro 4dr manual,1,0,0,0,0,0,1,0,33430,30366,3.0,6,220,17,26,3583,104,179,70
12,Audi A4 3.0 Quattro convertible 2dr,1,0,0,0,0,0,1,0,44240,40075,3.0,6,220,18,25,4013,105,180,70
13,Audi A41.8T convertible 2dr,1,0,0,0,0,0,0,0,35940,32506,1.8,4,170,23,30,3638,105,180,70
14,Audi A6 2.7 Turbo Quattro 4dr,1,0,0,0,0,0,1,0,42840,38840,2.7,6,250,18,25,3836,109,192,71
15,Audi A6 3.0 4dr,1,0,0,0,0,0,0,0,36640,33129,3.0,6,220,20,27,3561,109,192,71
16,Audi A6 3.0 Avant Quattro,0,0,0,1,0,0,1,0,40840,37060,3.0,6,220,18,25,4035,109,192,71
17,Audi A6 3.0 Quattro 4dr,1,0,0,0,0,0,1,0,39640,35992,3.0,6,220,18,25,3880,109,192,71
18,Audi A6 4.2 Quattro 4dr,1,0,0,0,0,0,1,0,49690,44936,4.2,8,300,17,24,4024,109,193,71
19,Audi A8 L Quattro 4dr,1,0,0,0,0,0,1,0,69190,64740,4.2,8,330,17,24,4399,121,204,75
20,Audi RS 6 4dr,0,1,0,0,0,0,0,0,84600,76417,4.2,8,450,15,22,4024,109,191,78
21,Audi S4 Avant Quattro,0,0,0,1,0,0,1,0,49090,44446,4.2,8,340,15,21,3936,104,179,70
22,Audi S4 Quattro 4dr,1,0,0,0,0,0,1,0,48040,43556,4.2,8,340,14,20,3825,104,179,70
23,Audi TT 1.8 convertible 2dr (coupe),0,1,0,0,0,0,0,0,35940,32512,1.8,4,180,20,28,3131,95,159,73
24,Audi TT 1.8 Quattro 2dr (convertible),0,1,0,0,0,0,1,0,37390,33891,1.8,4,225,20,28,2921,96,159,73
25,Audi TT 3.2 coupe 2dr (convertible),0,1,0,0,0,0,1,0,40590,36739,3.2,6,250,21,29,3351,96,159,73
26,BMW 325Ci 2dr,1,0,0,0,0,0,0,1,30795,28245,2.5,6,184,20,29,3197,107,177,69
27,BMW 325Ci convertible 2dr,1,0,0,0,0,0,0,1,37995,34800,2.5,6,184,19,27,3560,107,177,69
28,BMW 325i 4dr,1,0,0,0,0,0,0,1,28495,26155,2.5,6,184,20,29,3219,107,176,69
29,BMW 325xi 4dr,1,0,0,0,0,0,1,0,30245,27745,2.5,6,184,19,27,3461,107,176,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,Toyota Tacoma,0,0,0,0,0,1,0,1,12800,11879,2.4,4,142,22,27,2750,103,*,*
399,Toyota Tundra Access Cab V6 SR5,0,0,0,0,0,1,1,0,25935,23520,3.4,6,190,14,17,4435,128,*,*
400,Toyota Tundra Regular Cab V6,0,0,0,0,0,1,0,1,16495,14978,3.4,6,190,16,20,3925,128,*,*
401,Volkswagen Golf GLS 4dr,1,0,0,0,0,0,0,0,18715,17478,2.0,4,115,24,31,2897,99,165,68
402,Volkswagen GTI 1.8T 2dr hatch,1,0,0,0,0,0,0,0,19825,18109,1.8,4,180,24,31,2934,99,168,68
403,Volkswagen Jetta GL,0,0,0,1,0,0,0,0,19005,17427,2.0,4,115,24,30,3034,99,174,68
404,Volkswagen Jetta GLI VR6 4dr,1,0,0,0,0,0,0,0,23785,21686,2.8,6,200,21,30,3179,99,172,68
405,Volkswagen Jetta GLS TDI 4dr,1,0,0,0,0,0,0,0,21055,19638,1.9,4,100,38,46,3003,99,172,68
406,Volkswagen New Beetle GLS 1.8T 2dr,1,0,0,0,0,0,0,0,21055,19638,1.8,4,150,24,31,2820,99,161,68
407,Volkswagen New Beetle GLS convertible 2dr,1,0,0,0,0,0,0,0,23215,21689,2.0,4,115,24,30,3082,99,161,68
408,Volkswagen Passat GLS 1.8T,0,0,0,1,0,0,0,0,24955,22801,1.8,4,170,22,31,3338,106,184,69
409,Volkswagen Passat GLS 4dr,1,0,0,0,0,0,0,0,23955,21898,1.8,4,170,22,31,3241,106,185,69
410,Volkswagen Passat GLX V6 4MOTION 4dr,1,0,0,0,0,0,0,0,33180,30583,2.8,6,190,19,26,3721,106,185,69
411,Volkswagen Passat W8,0,0,0,1,0,0,0,0,40235,36956,4.0,8,270,18,25,4067,106,184,69
412,Volkswagen Passat W8 4MOTION 4dr,1,0,0,0,0,0,0,0,39235,36052,4.0,8,270,18,25,3953,106,185,69
413,Volkswagen Phaeton 4dr,1,0,0,0,0,0,0,0,65000,59912,4.2,8,335,*,*,5194,118,204,75
414,Volkswagen Phaeton W12 4dr,1,0,0,0,0,0,0,0,75000,69130,6.0,12,420,*,*,5399,118,204,75
415,Volkswagen Touareg V6,0,0,1,0,0,0,1,0,35515,32243,3.2,6,220,15,20,5086,112,187,76
416,Volvo C70 HPT convertible 2dr,1,0,0,0,0,0,0,0,42565,40083,2.3,5,242,20,26,3450,105,186,72
417,Volvo C70 LPT convertible 2dr,1,0,0,0,0,0,0,0,40565,38203,2.4,5,197,21,28,3450,105,186,72
418,Volvo S40 4dr,1,0,0,0,0,0,0,0,25135,23701,1.9,4,170,22,29,2767,101,178,68
419,Volvo S60 2.5 4dr,1,0,0,0,0,0,1,0,31745,29916,2.5,5,208,20,27,3903,107,180,71
420,Volvo S60 R 4dr,1,0,0,0,0,0,1,0,37560,35382,2.5,5,300,18,25,3571,107,181,71
421,Volvo S60 T5 4dr,1,0,0,0,0,0,0,0,34845,32902,2.3,5,247,20,28,3766,107,180,71
422,Volvo S80 2.5T 4dr,1,0,0,0,0,0,1,0,37885,35688,2.5,5,194,20,27,3691,110,190,72
423,Volvo S80 2.9 4dr,1,0,0,0,0,0,0,0,37730,35542,2.9,6,208,20,28,3576,110,190,72
424,Volvo S80 T6 4dr,1,0,0,0,0,0,0,0,45210,42573,2.9,6,268,19,26,3653,110,190,72
425,Volvo V40,0,0,0,1,0,0,0,0,26135,24641,1.9,4,170,22,29,2822,101,180,68
426,Volvo XC70,0,0,0,1,0,0,1,0,35145,33112,2.5,5,208,20,27,3823,109,186,73
427,Volvo XC90 T6,0,0,1,0,0,0,1,0,41250,38851,2.9,6,268,15,20,4638,113,189,75

In [4]:
data = data.sort_values(by='Small/Sporty/ Compact/Large Sedan')

In [5]:
data = data[:183]

In [6]:
data.head()

,Vehicle Name,Small/Sporty/ Compact/Large Sedan,Sports Car,SUV,Wagon,Minivan,Pickup,AWD,RWD,Retail Price,Dealer Cost,Engine Size (l),Cyl,HP,City MPG,Hwy MPG,Weight,Wheel Base,Len,Width
427,Volvo XC90 T6,0,0,1,0,0,0,1,0,41250,38851,2.9,6,268,15,20,4638,113,189,75
159,Honda CR-V LX,0,0,1,0,0,0,1,0,19860,18419,2.4,4,160,21,25,3258,103,179,70
160,Honda Element LX,0,0,1,0,0,0,1,0,18690,17334,2.4,4,160,21,24,3468,101,167,72
334,Porsche Boxster convertible 2dr,0,1,0,0,0,0,0,1,43365,37886,2.7,6,228,20,29,2811,95,170,70
162,Honda Odyssey EX,0,0,0,0,1,0,0,0,27450,24744,3.5,6,240,18,25,4365,118,201,76

In [7]:
cartype = data.loc[:,['Small/Sporty/ Compact/Large Sedan', 'Sports Car','SUV', 'Wagon', 'Minivan', 'Pickup']]

In [8]:
cartype

,Small/Sporty/ Compact/Large Sedan,Sports Car,SUV,Wagon,Minivan,Pickup
427,0,0,1,0,0,0
159,0,0,1,0,0,0
160,0,0,1,0,0,0
334,0,1,0,0,0,0
162,0,0,0,0,1,0
163,0,0,0,0,1,0
164,0,0,1,0,0,0
165,0,1,0,0,0,0
166,0,0,1,0,0,0
333,0,1,0,0,0,0
332,0,1,0,0,0,0
331,0,1,0,0,0,0
335,0,1,0,0,0,0
330,0,1,0,0,0,0
173,0,0,1,0,0,0
326,0,0,0,0,1,0
176,0,1,0,0,0,0
325,0,0,0,0,1,0
324,0,1,0,0,0,0
179,0,0,0,1,0,0
180,0,0,0,1,0,0
319,0,0,1,0,0,0
318,0,0,0,0,1,0
187,0,0,1,0,0,0
188,0,0,1,0,0,0
329,0,0,0,1,0,0
336,0,0,1,0,0,0
341,0,0,0,1,0,0
148,0,0,1,0,0,0
355,0,0,0,1,0,0
...,...,...,...,...,...,...
54,0,0,1,0,0,0
403,0,0,0,1,0,0
395,0,0,1,0,0,0
82,0,0,0,0,0,1
411,0,0,0,1,0,0
96,0,0,0,1,0,0
367,0,0,0,1,0,0
95,0,1,0,0,0,0
83,0,0,0,0,0,1
361,0,0,0,1,0,0
103,0,0,0,0,1,0
104,0,0,0,0,1,0
105,0,0,1,0,0,0
106,0,0,0,0,1,0
3,0,1,0,0,0,0
107,0,0,0,0,0,1
108,0,0,0,0,0,1
109,0,0,1,0,0,0
110,0,0,0,0,1,0
2,0,0,1,0,0,0
425,0,0,0,1,0,0
371,0,0,1,0,0,0
89,0,0,0,0,1,0
399,0,0,0,0,0,1
88,0,0,1,0,0,0
415,0,0,1,0,0,0
86,0,0,1,0,0,0
84,0,0,0,0,0,1
85,0,0,1,0,0,0
87,0,0,1,0,0,0

In [9]:
cartype['Small/Sporty/ Compact/Large Sedan'] = cartype['Small/Sporty/ Compact/Large Sedan'].map({1: 'Small/Sporty/ Compact/Large Sedan'})
cartype['Sports Car'] = cartype['Sports Car'].map({1: 'Sports Car'})
cartype['SUV'] = cartype['SUV'].map({1: 'SUV'})
cartype['Wagon'] = cartype['Wagon'].map({1: 'Wagon'})
cartype['Minivan'] = cartype['Minivan'].map({1: 'Minivan'})
cartype['Pickup'] = cartype['Pickup'].map({1: 'Pickup'})

In [10]:
cartype['type'] = cartype.max(axis=1)

In [11]:
cartype

,Small/Sporty/ Compact/Large Sedan,Sports Car,SUV,Wagon,Minivan,Pickup,type
427,NaN,NaN,SUV,NaN,NaN,NaN,SUV
159,NaN,NaN,SUV,NaN,NaN,NaN,SUV
160,NaN,NaN,SUV,NaN,NaN,NaN,SUV
334,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
162,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
163,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
164,NaN,NaN,SUV,NaN,NaN,NaN,SUV
165,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
166,NaN,NaN,SUV,NaN,NaN,NaN,SUV
333,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
332,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
331,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
335,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
330,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
173,NaN,NaN,SUV,NaN,NaN,NaN,SUV
326,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
176,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
325,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
324,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
179,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
180,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
319,NaN,NaN,SUV,NaN,NaN,NaN,SUV
318,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
187,NaN,NaN,SUV,NaN,NaN,NaN,SUV
188,NaN,NaN,SUV,NaN,NaN,NaN,SUV
329,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
336,NaN,NaN,SUV,NaN,NaN,NaN,SUV
341,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
148,NaN,NaN,SUV,NaN,NaN,NaN,SUV
355,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
...,...,...,...,...,...,...,...
54,NaN,NaN,SUV,NaN,NaN,NaN,SUV
403,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
395,NaN,NaN,SUV,NaN,NaN,NaN,SUV
82,NaN,NaN,NaN,NaN,NaN,Pickup,Pickup
411,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
96,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
367,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
95,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
83,NaN,NaN,NaN,NaN,NaN,Pickup,Pickup
361,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
103,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
104,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
105,NaN,NaN,SUV,NaN,NaN,NaN,SUV
106,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
3,NaN,Sports Car,NaN,NaN,NaN,NaN,Sports Car
107,NaN,NaN,NaN,NaN,NaN,Pickup,Pickup
108,NaN,NaN,NaN,NaN,NaN,Pickup,Pickup
109,NaN,NaN,SUV,NaN,NaN,NaN,SUV
110,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
2,NaN,NaN,SUV,NaN,NaN,NaN,SUV
425,NaN,NaN,NaN,Wagon,NaN,NaN,Wagon
371,NaN,NaN,SUV,NaN,NaN,NaN,SUV
89,NaN,NaN,NaN,NaN,Minivan,NaN,Minivan
399,NaN,NaN,NaN,NaN,NaN,Pickup,Pickup
88,NaN,NaN,SUV,NaN,NaN,NaN,SUV
415,NaN,NaN,SUV,NaN,NaN,NaN,SUV
86,NaN,NaN,SUV,NaN,NaN,NaN,SUV
84,NaN,NaN,NaN,NaN,NaN,Pickup,Pickup
85,NaN,NaN,SUV,NaN,NaN,NaN,SUV
87,NaN,NaN,SUV,NaN,NaN,NaN,SUV

In [12]:
Type = cartype["type"]
Type

427           SUV
159           SUV
160           SUV
334    Sports Car
162       Minivan
163       Minivan
164           SUV
165    Sports Car
166           SUV
333    Sports Car
332    Sports Car
331    Sports Car
335    Sports Car
330    Sports Car
173           SUV
326       Minivan
176    Sports Car
325       Minivan
324    Sports Car
179         Wagon
180         Wagon
319           SUV
318       Minivan
187           SUV
188           SUV
329         Wagon
336           SUV
341         Wagon
148           SUV
355         Wagon
          ...
54            SUV
403         Wagon
395           SUV
82         Pickup
411         Wagon
96          Wagon
367         Wagon
95     Sports Car
83         Pickup
361         Wagon
103       Minivan
104       Minivan
105           SUV
106       Minivan
3      Sports Car
107        Pickup
108        Pickup
109           SUV
110       Minivan
2             SUV
425         Wagon
371           SUV
89        Minivan
399        Pickup
88            SUV
415           SUV
86            SUV
84         Pickup
85            SUV
87            SUV
Name: type, dtype: object

In [13]:
car2 = pd.DataFrame()
car2['name']= data['Vehicle Name']
car2['type']= cartype["type"]
car2['retail_price']= data['Retail Price']
car2['engine_size']= data['Engine Size (l)']
car2['hp']= data['HP']
car2['mpg_city']= data['City MPG']
car2['mpg_hwy']= data['Hwy MPG']
car2['weight']= data['Weight']
car2['wheel_base']= data['Wheel Base']
car2.head()

,name,type,retail_price,engine_size,hp,mpg_city,mpg_hwy,weight,wheel_base
427,Volvo XC90 T6,SUV,41250,2.9,268,15,20,4638,113
159,Honda CR-V LX,SUV,19860,2.4,160,21,25,3258,103
160,Honda Element LX,SUV,18690,2.4,160,21,24,3468,101
334,Porsche Boxster convertible 2dr,Sports Car,43365,2.7,228,20,29,2811,95
162,Honda Odyssey EX,Minivan,27450,3.5,240,18,25,4365,118

In [14]:
car2.to_csv('a5_data2_your_net_id.csv')